### ISSUE TITLE
SectionEdit button placement after upgrade to Detritus 

### ISSUE THREAD

**Issue by sirconny** [samfisch/dokuwiki-template-arctic#11]
Not a big issue but after updating to Detritus I noticed that the sectionedit button has moved to the left side which actually is a bit disturbing. It is also seems a bit bigger.

**Comment by mprins** [comment]
this might be related to splitbrain/dokuwiki#1231 and arctic using `input.button` as a css selector to float right.

you could check if the sectionedit button is a `button` or an `input` (of type submit) element

**Comment by sirconny** [comment]
Spot on mprins.
Changed according to https://github.com/splitbrain/dokuwiki/pull/1231 in lib/tpl/arctic/design.css (line 217) 
Now the file looks like this.
```
      div.dokuwiki div.secedit input.button,
      div.dokuwiki div.secedit button { 
```
and after that the sectionedit button moved to the right and also got back its old look.  
Thanks for an excellent answer.

**Comment by mprins** [comment]
I started a PR ( #12 ) but I'm short in time atm so if anyone has more time they are welcome to it
